(define (problem t1)
  (:domain testpd)
  (:objects a1 - agent l1 l2 - loc)
  (:init (at a1 l1)
         (= (dist l1 l1) 1) (= (dist l1 l2) 5)
         (= (dist l2 l1) 5) (= (dist l2 l2) 1))
  (:goal (at a1 l2))
  (:metric minimize (total-time))
)
