(define (problem p2)
  (:domain cafeteria-hot)
  (:objects waiter1 - waiter
            mesa1 mesa2 mesa3 mesa4 - table
            o1 o2 o3 o4 - order)
  (:init (barista-free) (at waiter1 bar) (hand-free waiter1) (no-tray waiter1) (tray-at-bar)
         (= (tray-load waiter1) 0)
         (= (travel-empty bar mesa1) 2) (= (travel-empty bar mesa2) 2)
         (= (travel-empty bar mesa3) 3) (= (travel-empty bar mesa4) 3)
         (= (travel-empty mesa1 bar) 2) (= (travel-empty mesa2 bar) 2)
         (= (travel-empty mesa3 bar) 3) (= (travel-empty mesa4 bar) 3)
         (= (travel-empty mesa1 mesa2) 1) (= (travel-empty mesa1 mesa3) 1)
         (= (travel-empty mesa1 mesa4) 1) (= (travel-empty mesa2 mesa1) 1)
         (= (travel-empty mesa2 mesa3) 1) (= (travel-empty mesa2 mesa4) 1)
         (= (travel-empty mesa3 mesa1) 1) (= (travel-empty mesa3 mesa2) 1)
         (= (travel-empty mesa3 mesa4) 1) (= (travel-empty mesa4 mesa1) 1)
         (= (travel-empty mesa4 mesa2) 1) (= (travel-empty mesa4 mesa3) 1)
         (= (travel-tray bar mesa1) 4) (= (travel-tray bar mesa2) 4)
         (= (travel-tray bar mesa3) 6) (= (travel-tray bar mesa4) 6)
         (= (travel-tray mesa1 bar) 4) (= (travel-tray mesa2 bar) 4)
         (= (travel-tray mesa3 bar) 6) (= (travel-tray mesa4 bar) 6)
         (= (travel-tray mesa1 mesa2) 2) (= (travel-tray mesa1 mesa3) 2)
         (= (travel-tray mesa1 mesa4) 2) (= (travel-tray mesa2 mesa1) 2)
         (= (travel-tray mesa2 mesa3) 2) (= (travel-tray mesa2 mesa4) 2)
         (= (travel-tray mesa3 mesa1) 2) (= (travel-tray mesa3 mesa2) 2)
         (= (travel-tray mesa3 mesa4) 2) (= (travel-tray mesa4 mesa1) 2)
         (= (travel-tray mesa4 mesa2) 2) (= (travel-tray mesa4 mesa3) 2)
         (= (clean-time mesa1) 4) (= (clean-time mesa2) 4)
         (= (clean-time mesa3) 8) (= (clean-time mesa4) 4)
         (pending o1) (pending o2) (pending o3) (pending o4)
         (cold o1) (cold o2) (hot o3) (hot o4)
         (for-table o1 mesa3) (for-table o2 mesa3)
         (for-table o3 mesa3) (for-table o4 mesa3)
         (dirty mesa1))
  (:goal (and (served o1) (served o2) (served o3) (served o4)
              (clean mesa1) (tray-at-bar)))
  (:metric minimize (total-time))
)
